logging:
  level:
    com.anand.LmsBoot: DEBUG
spring:  datasource:    url: jdbc:mysql://localhost:3306/lms?useSSL=false
    username: root
    password: root
    hikari:      connection-timeout: 60000
      maximum-pool-size: 5  jpa:    hibernate:      ddl-auto: update